import os
import sys



os.system('clear')
print()
print("DonutPac - Package Manager for DonutOS")
print("-------------------------------------------")
print()
print("To install a package just type the package name in the prompt..")
print()
donut = ""
while donut != "exit" or donut != "quit":
    donut = input("DonutPac > ").lower()
    if donut == "exit" or donut == "quit":
        break
    else:
        if "zlib" in donut:
            print()
            print("Connecting to the Server...")
            print("Loading Repository Data....")
            print()
            print("The following package(s) are going to be installed: ")
            print("\t Zlib-1.2.13")
            confirm = input("Are you sure you want to install it? (y/n) : ")
            if confirm == "y" or confirm == "yes":
                print("Downloading Zlib-1.2.13")
                os.system('wget http://zlib.net/zlib-1.2.13.tar.gz')
                print("Downloaded Zlib-1.2.13")
                print()
                print("Please wait... Preparing to Configure and Install Zlib..")
                print("Downloading Configuration Script and Installing Zlib...")
                os.system('wget https://raw.githubusercontent.com/gauthamnair2005/DonutLinux/main/zlib_ci.sh')
                os.system('bash zlib_ci.sh')
                os.system('sudo rm -Rf zlib-1.2.13')
                os.system('sudo rm zlib_ci.sh')
                print("Executed")
                print()
            else:
                print()
                print("Zlib Not Installed")
                print()
        elif "GCC" in donut:
            print()
            print("Connecting to the Server...")
            print("Loading Repository Data....")
            print()
            print("The following package(s) are going to be installed: ")
            print("\t GCC-13.1.0")
            print("\t MPFR")
            print("\t MPC")
            print("\t GMP")
            confirm = input("Are you sure you want to install these packages? (y/n) : ")
            if confirm == "y" or confirm == "yes":
                print("Downloading GCC-13.1.0, GMP, MPC, MPFR")
                os.system('wget https://ftp.gnu.org/gnu/gcc/gcc-13.1.0/gcc-13.1.0.tar.xz')
                os.system('wget https://ftp.gnu.org/gnu/gmp/gmp-6.2.1.tar.xz')
                os.system('wget https://ftp.gnu.org/gnu/mpc/mpc-1.3.1.tar.gz')
                os.system('wget https://ftp.gnu.org/gnu/mpfr/mpfr-4.2.0.tar.xz')
                print("Downloaded GCC-13.1.0, GMP, MPC, MPFR")
                print()
                print("Please wait... Preparing to Configure and Install GCC...")
                print("Downloading Configuration Script and Installing GCC...")
                os.system('wget https://raw.githubusercontent.com/gauthamnair2005/DonutLinux/main/gcc_ci.sh')
                os.system('bash gcc_ci.sh')
                os.system('sudo rm -Rf gcc-13.1.0')
                os.system('sudo rm gcc_ci.sh')
                os.system('sudo rm gcc-13.1.0.tar.xz')
                print("Executed")
                print()
        elif "grub" in donut:
            print()
            print("Connecting to the Server...")
            print("Loading Repository Data....")
            print()
            print("The following package(s) are going to be installed: ")
            print("\t GRUB-2.06")
            confirm = input("Are you sure you want to install it? (y/n) : ")
            if confirm == "y" or confirm == "yes":
                print("Downloading GRUB-2.06")
                os.system('wget https://ftp.gnu.org/gnu/grub/grub-2.06.tar.xz')
                print("Downloaded GRUB-2.06")
                print()
                print("Please wait... Preparing to Configure and Install GRUB...")
                print("Downloading Configuration Script and Installing GRUB...")
                os.system('wget https://raw.githubusercontent.com/gauthamnair2005/DonutLinux/main/grub_ci.sh')
                os.system('bash grub_ci.sh')
                os.system('sudo rm -Rf grub-2.06')
                os.system('sudo rm grub_ci.sh')
                os.system('sudo rm grub-2.06.tar.xz')
                print("Executed")
                print()
            else:
                print()
                print("GRUB Not Installed")
                print()
        elif donut == "developer":
            print()
            print("Gautham Nair")
            print()
            print("DonutPac for DonutOS/DonutLinux")
            print()
        elif donut == "codename":
            print()
            print("Munnar")
        else:
            print()
            print("Connecting to the Server...")
            print("Loading Repository Data....")
            print()
            print("The package ", donut , " couldn't be located in DonutPac's Index")
            print()
